Kien

In [ ]:
import numpy as np

In [ ]:
X = np.array([
    [2],
    [7],
    [9],
    [3],
    [10],
    [6],
    [1],
    [8]
]
)

In [ ]:
X.shape

(8, 1)

In [ ]:
ones = np.ones_like(X)
ones

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [ ]:
X = np.concatenate ((X,ones), axis =1)
X.shape

(8, 2)

In [ ]:
y = np.array([
    [13],
    [35],
    [41],
    [19],
    [45],
    [28],
    [10],
    [55]
])

In [ ]:
# theta = np.random.normal(size = 2).reshape(2,1)
theta = np.array([[1],[1]])
theta

array([[1],
       [1]])

In [ ]:
def hypo(X,theta):
  return X.dot(theta)

In [ ]:
hypo(X,theta).shape

(8, 1)

In [ ]:
sum((hypo(X,theta)-y)**2)/8

array([1493.56319363])

In [ ]:
a = np.array([[1],[2]])
b = np.array([[3],[4]])
np.dot(a,b.T)

array([[3, 4],
       [6, 8]])

**Lập trình Gradient**

In [ ]:
def gradient(X,y,theta,m):
  gradient = 1/m * X.T.dot(hypo(X,theta) - y) # (2 x 1)
  return gradient
  #Linear Regression Model

In [ ]:
def cost(X, y, theta, m):
  # Lập trình tại đây
  v = sum((hypo(X,theta)-y)**2)/(2*m)
  return v

In [ ]:
# cost(X, y, theta, m)

In [ ]:
# hyperparameters
# fine tune
m = 8
learning_rate = 0.001
epochs = 300

In [ ]:
# gradient(X,y,theta,m)

array([[-171.875],
       [ -24.   ]])

In [ ]:
for i in range(epochs):
  # Tính gradient
  grad = gradient(X,y,theta,m)
  # print(grad)
  theta = theta - learning_rate * grad
  if (i+1) % 3 == 0:
    print('Cost is: {}'.format(cost(X,y,theta,m)))

Cost is: [17.4110641]
Cost is: [17.40950166]
Cost is: [17.40794134]
Cost is: [17.40638315]
Cost is: [17.40482708]
Cost is: [17.40327313]
Cost is: [17.4017213]
Cost is: [17.40017157]
Cost is: [17.39862396]
Cost is: [17.39707845]
Cost is: [17.39553505]
Cost is: [17.39399375]
Cost is: [17.39245455]
Cost is: [17.39091744]
Cost is: [17.38938242]
Cost is: [17.3878495]
Cost is: [17.38631866]
Cost is: [17.38478991]
Cost is: [17.38326323]
Cost is: [17.38173864]
Cost is: [17.38021612]
Cost is: [17.37869567]
Cost is: [17.37717729]
Cost is: [17.37566098]
Cost is: [17.37414674]
Cost is: [17.37263456]
Cost is: [17.37112443]
Cost is: [17.36961636]
Cost is: [17.36811034]
Cost is: [17.36660638]
Cost is: [17.36510446]
Cost is: [17.36360458]
Cost is: [17.36210675]
Cost is: [17.36061096]
Cost is: [17.3591172]
Cost is: [17.35762548]
Cost is: [17.35613579]
Cost is: [17.35464812]
Cost is: [17.35316248]
Cost is: [17.35167887]
Cost is: [17.35019727]
Cost is: [17.34871769]
Cost is: [17.34724012]
Cost is: [17.34

In [ ]:
X_new = np.array([[40,1]])
hypo(X_new,theta)

array([[194.64645382]])