In [ ]:
import tensorflow_datasets as tfds

In [ ]:
import tensorflow as tf

In [ ]:
dataset, info = tfds.load('imdb_reviews/subwords8k', with_info=True, as_supervised=True)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteHY00PH/imdb_reviews-train.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteHY00PH/imdb_reviews-test.tfrecord


  0%|          | 0/25000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteHY00PH/imdb_reviews-unsupervised.tfrecord


  0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0. Subsequent calls will reuse this data.


In [ ]:
train_dataset, test_dataset = dataset['train'], dataset['test']

In [ ]:
list(train_dataset.take(1))

[(<tf.Tensor: shape=(163,), dtype=int64, numpy=
  array([  62,   18,   41,  604,  927,   65,    3,  644, 7968,   21,   35,
         5096,   36,   11,   43, 2948, 5240,  102,   50,  681, 7862, 1244,
            3, 3266,   29,  122,  640,    2,   26,   14,  279,  438,   35,
           79,  349,  384,   11, 1991,    3,  492,   79,  122,  188,  117,
           33, 4047, 4531,   14,   65, 7968,    8, 1819, 3947,    3,   62,
           27,    9,   41,  577, 5044, 2629, 2552, 7193, 7961, 3642,    3,
           19,  107, 3903,  225,   85,  198,   72,    1, 1512,  738, 2347,
          102, 6245,    8,   85,  308,   79, 6936, 7961,   23, 4981, 8044,
            3, 6429, 7961, 1141, 1335, 1848, 4848,   55, 3601, 4217, 8050,
            2,    5,   59, 3831, 1484, 8040, 7974,  174, 5773,   22, 5240,
          102,   18,  247,   26,    4, 3903, 1612, 3902,  291,   11,    4,
           27,   13,   18, 4092, 4008, 7961,    6,  119,  213, 2774,    3,
           12,  258, 2306,   13,   91,   29,  171,  

In [ ]:
tokenizer = info.features['text'].encoder

In [ ]:
BUFFER_SIZE = 10000
BATCH_SIZE = 64

In [ ]:
train_dataset = train_dataset.shuffle(BUFFER_SIZE)

In [ ]:
len(train_dataset)

25000

In [ ]:
train_dataset = train_dataset.padded_batch(BATCH_SIZE)

In [ ]:
test_dataset = test_dataset.padded_batch(BATCH_SIZE)

In [ ]:
list(train_dataset.take(2))

[(<tf.Tensor: shape=(64, 2008), dtype=int64, numpy=
  array([[8017, 3106, 8026, ...,    0,    0,    0],
         [1698,    2,   55, ...,    0,    0,    0],
         [ 492, 2642, 4898, ...,    0,    0,    0],
         ...,
         [  12,   31,  550, ...,    0,    0,    0],
         [1679, 2262, 7974, ..., 7986, 7976,  283],
         [  62,   27,    9, ...,    0,    0,    0]])>,
  <tf.Tensor: shape=(64,), dtype=int64, numpy=
  array([1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
         0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
         0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0])>),
 (<tf.Tensor: shape=(64, 1491), dtype=int64, numpy=
  array([[  62,    9,    1, ...,    0,    0,    0],
         [ 444,   18,  122, ...,    0,    0,    0],
         [3281,   52,    4, ...,    0,    0,    0],
         ...,
         [  19, 1568, 6751, ...,    0,    0,    0],
         [2694, 3420,    9, ...,    0,    0,    0],
         [  12,  174,  

# Simple RNN

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, RNN, Dense, LSTM, Bidirectional, SimpleRNN

In [ ]:
tokenizer.vocab_size

8185

In [ ]:
model1 = Sequential()
model1.add(Embedding(tokenizer.vocab_size, 64))
model1.add(SimpleRNN(32))


In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 64)          523840    
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                3104      
                                                                 
Total params: 526,944
Trainable params: 526,944
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.add(Dense(16, activation='relu'))

In [ ]:
model1.add(Dense(1, activation='sigmoid'))

In [ ]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model1.fit(train_dataset, epochs=10, validation_data=test_dataset)

# LSTM

In [ ]:
model2 = Sequential()
model2.add(Embedding(tokenizer.vocab_size, 64))
model2.add(LSTM(32))
model2.add(Dense(16, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

In [ ]:
model2.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 64)          523840    
                                                                 
 lstm (LSTM)                 (None, 32)                12416     
                                                                 
 dense (Dense)               (None, 16)                528       
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 536,801
Trainable params: 536,801
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model2.fit(train_dataset, epochs=10, validation_data=test_dataset)

# Bidirectional

In [ ]:
model3 = Sequential()
model3.add(Embedding(tokenizer.vocab_size, 64))
model3.add(Bidirectional(LSTM(32)))
model3.add(Dense(32, activation='relu'))
model3.add(Dense(1, activation='sigmoid'))

In [ ]:
model3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 64)          523840    
                                                                 
 bidirectional (Bidirectiona  (None, 64)               24832     
 l)                                                              
                                                                 
 dense_2 (Dense)             (None, 32)                2080      
                                                                 
 dense_3 (Dense)             (None, 1)                 33        
                                                                 
Total params: 550,785
Trainable params: 550,785
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model3.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model3.fit(train_dataset, epochs=10, validation_data=test_dataset)

Epoch 1/10
391/391 [==============================] - 53s 126ms/step - loss: 0.5763 - acc: 0.6939 - val_loss: 0.5983 - val_acc: 0.6715
Epoch 2/10
391/391 [==============================] - 46s 118ms/step - loss: 0.4312 - acc: 0.8046 - val_loss: 0.4434 - val_acc: 0.8076
Epoch 3/10
391/391 [==============================] - 47s 120ms/step - loss: 0.3408 - acc: 0.8587 - val_loss: 0.6053 - val_acc: 0.6782
Epoch 4/10
391/391 [==============================] - 47s 119ms/step - loss: 0.3193 - acc: 0.8659 - val_loss: 0.4411 - val_acc: 0.8249
Epoch 5/10
391/391 [==============================] - 48s 122ms/step - loss: 0.2128 - acc: 0.9214 - val_loss: 0.4435 - val_acc: 0.8279
Epoch 6/10
391/391 [==============================] - 48s 121ms/step - loss: 0.1627 - acc: 0.9426 - val_loss: 0.4976 - val_acc: 0.8200
Epoch 7/10
391/391 [==============================] - 47s 120ms/step - loss: 0.1480 - acc: 0.9484 - val_loss: 0.5416 - val_acc: 0.8210
Epoch 8/10
391/391 [==============================] - 4

# Deep Bidirectional LSTM

In [ ]:
model4 = Sequential()
model4.add(Embedding(tokenizer.vocab_size, 64))
model4.add(Bidirectional(LSTM(64, return_sequences=True))) # (64 * 64 * 8 + 64 * 4) * 2
model4.add(Bidirectional(LSTM(64, return_sequences=True))) # (64 * 64 * 8 + 64 * 4) * 2
model4.add(Bidirectional(LSTM(32))) # (128 * 32 * 4 + 32 * 32 * 4 + 32 * 4) * 2
model4.add(Dense(32, activation='relu'))
model4.add(Dense(1, activation='sigmoid'))

In [ ]:
model4.summary()

In [ ]:
model4.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

In [ ]:
model4.fit(train_dataset, epochs=10, validation_data=test_dataset)