Stochastic Gradient Descent

In [1]:
import numpy as np

In [2]:
X = np.array([
  [2],
  [7],
  [9],
  [3],
  [10],
  [6],
  [1],
  [8]
]
)

In [3]:
y = np.array(
    [
     [13],
     [35],
     [41],
     [19],
     [45],
     [28],
     [10],
     [55],

    ]
)

In [4]:
ones = np.ones_like(X)

In [5]:
X = np.concatenate((X, ones), axis=1)

In [6]:
X

array([[ 2,  1],
       [ 7,  1],
       [ 9,  1],
       [ 3,  1],
       [10,  1],
       [ 6,  1],
       [ 1,  1],
       [ 8,  1]])

In [7]:
X[1]

array([7, 1])

In [8]:
def predict(theta, x):
  return x.T.dot(theta)

In [9]:
def cost(X, y, theta, m):
  return 1/(2 *m)* np.sum((X.dot(theta) - y)**2)

In [10]:
from sklearn.utils import shuffle

In [ ]:
def SGD(X, y, theta, learning_rate, epochs):

  print(X, y)
  # Step 2: Update theta
  m = len(X)
  for i in range(epochs):
    # Step 1: Shuffle dataset
    X, y = shuffle(X, y)
    for k in range(m):
      error = predict(theta, X[k]) - y[k]
      for j in range(len(theta)):
        theta[j] = theta[j] - learning_rate * error * X[k][j]
    if (i + 1) % 100 == 0:
      print("Loss is {}".format(cost(X, y, theta, m)))

In [ ]:
theta = np.random.normal(size=2).reshape((2, 1))

In [ ]:
epochs = 3000
learning_rate = 0.001

In [ ]:
SGD(X, y, theta, learning_rate, epochs)

In [ ]:
predict(theta, np.array([40, 1]))

array([180.87842133])

In [ ]:
X[0].shape

(2,)