In [2]:
import tensorflow as tf

In [ ]:
#Cach 1
# can tinh dao ham theo t cua ham số f(x,y) = (sint)^3*cost
def cal(t):
  x = tf.math.sin(t)
  y = tf.math.cos(t)
  return 3*x**2*y*tf.math.cos(t)-x**3*tf.math.sin(t)
# cal(4)

In [ ]:
cal(4.0)

<tf.Tensor: shape=(), dtype=float32, numpy=0.40607968>

In [ ]:
# print(tf.math.sin(3.0))

In [ ]:
t = tf.constant(4.0)

with tf.GradientTape() as g: # g là tf.GradientTape
  g.watch(t) # quan sát biến t
  x = tf.math.sin(t)
  y = tf.math.cos(t)
  f = x**3*y
dy_dt = g.gradient(f,t) # dao ham cua bien f theo t
print(dy_dt)

tf.Tensor(0.40607968, shape=(), dtype=float32)


In [ ]:
# Hàm y = log(x**3sin(x))

x = tf.constant(0.0)
with tf.GradientTape() as g:
  g.watch(x)
  y = tf.math.log(x**3 * tf.math.sin(x))
dy_dx = g.gradient(y,x)
print(dy_dx)

tf.Tensor(nan, shape=(), dtype=float32)


In [ ]:
# Đạo hàm của hảm y = sinx

x = tf.constant(0.0)
with tf.GradientTape() as g:
  g.watch(x)
  y = tf.math.sin(x)
dy_dx = g.gradient(y,x)
print(dy_dx)

tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
# quy tắc chuỗi: x -> x**3 -> sin(x**3)
                      # g1 -- -> g2

x = tf.constant(4.0)
with tf.GradientTape() as g:
  g.watch(x)
  g1 = x**3
  g2 = tf.math.sin(g1)
dg2_dx = g.gradient(g2,x)
dg2_dx


# cach2
x = tf.constant(4.0)
with tf.GradientTape() as g:
  g.watch(x)
  f = tf.math.sin(x**3)
df_dx = g.gradient(f,x)
print(df_dx)

tf.Tensor(18.809147, shape=(), dtype=float32)


In [ ]:
# Tinh dao ham cua fx = ln(x**3)
# su dung quy tac chuoi x - > x**3 -> ln(x**3)

x = tf.constant(1.0)
with tf.GradientTape() as g:
  g.watch(x)
  g1 = x**3
  g2 = tf.math.log(g1)

dg2_dx = g.gradient(g2,x)
print(dg2_dx)

tf.Tensor(3.0, shape=(), dtype=float32)


In [5]:
# Tinh dao ham rieng theo x và theo y của hàm số fx = 2x**2 + 6y -30


x = tf.constant(0.6)
y = tf.constant(0.8)
with tf.GradientTape(persistent = True) as g:
  g.watch(x)
  g.watch(y)
  f = 2*x**2+6*y-30

df_dx = g.gradient(f,x)
df_dy = g.gradient(f,y)
print([df_dx,df_dy])

[<tf.Tensor: shape=(), dtype=float32, numpy=2.4>, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>]


In [9]:
# t = tf.constant(4.0)
x = tf.constant(-2.0)
y = tf.constant(5.0)
z = tf.constant(-4.0)


with tf.GradientTape(persistent = True) as g:
  g.watch(x) # quan sát biến t
  g.watch(y) # quan sát biến y
  g.watch(z) # quan sát biến z
  # x = tf.math.sin(t)
  # y = tf.math.cos(t)
  f = (x+y)*z
df_dx = g.gradient(f,x) # dao ham cua bien f theo t
print(df_dx)

tf.Tensor(-4.0, shape=(), dtype=float32)


In [38]:
z = -4.0
q = [[-2.0], [5.0]]
# f = tf.matmul(z,q)


#step1: khai bao constant
z = tf.constant(z,dtype=tf.float32)
q = tf.constant(q,dtype=tf.float32)
with tf.GradientTape(persistent=True) as g:
   # persistent = True de watch dc nhieu bien
   g.watch(z)
   g.watch(q)
   f = tf.math.scalar_mul(z, q)
  #  f = tf.matmul(W,x)  # tuong duong với phép nhân 2 Mat trong numpy W@x 3x3 @ 3x1 -> MAT 3x1
   jfz = g.jacobian(f,z) # tập hợp các Gradient giữa từng phần từ của f và z -> có chiều là x 2x1 (chiều của f) 2x1 và (chiều của z là 1 scalar) -> 2x1
   jfq = g.jacobian(f,q) # có chiều 2x1x2x1
   gfz = g.gradient(f,z)
   gfq = g.gradient(f,q)


print('Jacobian jfz', jfz)
print('Jacobian jfq:', jfq)
print('gradient gfz',gfz)
print('gradient gfq',gfq)
# print(jfx[1][0][2][0])



Jacobian jfz tf.Tensor(
[[-2.]
 [ 5.]], shape=(2, 1), dtype=float32)
Jacobian jfq: tf.Tensor(
[[[[-4.]
   [-0.]]]


 [[[-0.]
   [-4.]]]], shape=(2, 1, 2, 1), dtype=float32)
gradient gfz tf.Tensor(3.0, shape=(), dtype=float32)
gradient gfq tf.Tensor(
[[-4.]
 [-4.]], shape=(2, 1), dtype=float32)


In [41]:
z

<tf.Tensor: shape=(), dtype=float32, numpy=-4.0>

In [32]:
import numpy as np
z = -4
q = [[-2.0], [5.0]]
np.array(z).dot(np.array(q))

array([[  8.],
       [-20.]])

In [26]:
np.array(z).shape

(1, 2)