In [ ]:
# Import Relevant libraries
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Tạo sample **Dataset**

In [ ]:
import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(0)

# Generate a sample dataset based on the structure and ranges observed in the image
# Assumed ranges based on the image provided
number_of_samples = 1000
rooms_range = (1, 1000)  # x1
beds_range = (1, 1000)   # x2
population_range = (10000, 100000)  # x3
price_range = (10000 , 100000000)  # y

# Create a DataFrame with random values within the observed ranges
sample_dataset = pd.DataFrame({
    'num_rum': np.random.uniform(rooms_range[0], rooms_range[1], number_of_samples),
    'num_beds': np.random.uniform(beds_range[0], beds_range[1], number_of_samples),
    'poplulation': np.random.uniform(population_range[0], population_range[1], number_of_samples),
    'house_price': np.random.uniform(price_range[0], price_range[1], number_of_samples)
})

# Round the values to simulate the appearance of the data in the image
sample_dataset = sample_dataset.round(1)

# Display the sample dataset
sample_dataset.head(20)

num_rum  num_beds  poplulation  house_price
0     549.3     593.3      83036.7   41402109.9
1     715.5      11.1      52847.6   62965534.1
2     603.2     476.4      57084.0   77860640.6
3     545.3     709.1      32546.9   85157263.9
4     424.2      44.9      64453.9   81643107.2
5     646.2     879.6      37261.4   16616048.1
6     438.1     520.6      61955.6   82840671.4
7     891.9      31.6      25271.0    5872319.6
8     963.7     225.2      24352.2   20025066.4
9     384.1     953.7      47532.7   62296442.7
10    791.9     582.7      48413.8   11478105.6
11    529.4     108.4      34129.8   60338726.0
12    568.5     288.3      21843.7   30803489.5
13    925.7     457.2      13528.9   42952363.8
14     72.0      21.9      12270.9   31521998.8
15     88.0     412.2      34439.5    7026655.1
16     21.2     490.0      51566.8   50080867.7
17    832.8     244.4      75361.9   96360308.4
18    778.4     589.1      52738.5   61182217.0
19    870.1     753.5      91364.6   30010186.8

Các bước để tạo 1 mô hình hồi quy tuyến tính với Gradient Decents:

---


- Bước 1: tạo vector theta:
- Bước 2: Tạo Hàm hypo h(theta) = theta + theta1 * x1 + .... + theta_n *x_n
- Bước 3: Define hàm Loss (trên 1 điểm dữ liệu) L = (h(theta) - y)^2
- Bước 4: Define hàm Cost Function (Trên toàn bộ tập dữ liệu): $$ J(\theta) = \frac{1}{2m} \sum_{i=1}^{m} \left(h_\theta(x^{(i)}) - y^{(i)}\right)^2 $$





In [ ]:
X = sample_dataset.drop('house_price',axis = 1)
y = sample_dataset['house_price']
# print(X,y)
print(X)
print(y)

     num_rum  num_beds  poplulation
0      549.3     593.3      83036.7
1      715.5      11.1      52847.6
2      603.2     476.4      57084.0
3      545.3     709.1      32546.9
4      424.2      44.9      64453.9
..       ...       ...          ...
995     98.6     791.5      94751.8
996    515.4     721.5      59151.9
997    938.5     480.6      39125.2
998    229.4     644.2      83219.1
999    677.5     502.3      72766.0

[1000 rows x 3 columns]
0      41402109.9
1      62965534.1
2      77860640.6
3      85157263.9
4      81643107.2
          ...    
995    34970440.3
996    43493014.2
997    83001994.7
998    93281290.2
999    30840760.1
Name: house_price, Length: 1000, dtype: float64


In [ ]:
# add thêm 1 cột vector 1
X_array = np.array(X)
X_with_ones = np.hstack((np.ones((X_array.shape[0], 1)), X_array))
X_with_ones

array([[1.00000e+00, 5.49300e+02, 5.93300e+02, 8.30367e+04],
       [1.00000e+00, 7.15500e+02, 1.11000e+01, 5.28476e+04],
       [1.00000e+00, 6.03200e+02, 4.76400e+02, 5.70840e+04],
       ...,
       [1.00000e+00, 9.38500e+02, 4.80600e+02, 3.91252e+04],
       [1.00000e+00, 2.29400e+02, 6.44200e+02, 8.32191e+04],
       [1.00000e+00, 6.77500e+02, 5.02300e+02, 7.27660e+04]])

In [ ]:
theta = np.random.normal(size=X_with_ones.shape[1]).reshape((X_with_ones.shape[1], 1))
theta

array([[ 0.55696832],
       [-1.7362418 ],
       [-0.37678411],
       [-0.90903233]])

In [ ]:
X_with_ones
# theta = np.random.normal(size=X_with_ones.shape[1]).reshape((X_with_ones.shape[1], 1))
hypo = X_with_ones.dot(theta)
y =  np.array(y).reshape(hypo.shape[0], 1)


# #step1: khai bao constant
X = tf.constant(X_with_ones,dtype=tf.float32)
theta = tf.constant(theta,dtype=tf.float32)
y = tf.constant(y,dtype=tf.float32)
with tf.GradientTape(persistent=True) as g:
#    # persistent = True de watch dc nhieu bien
   g.watch(X)
   g.watch(theta)
   g.watch(y)
   f = tf.reduce_mean(tf.square(tf.matmul(X,theta) - y))
   gfx = g.gradient(f,theta)

   jftheta = g.jacobian(f,theta)

# print(f)
# print()

# gfx_2 = 2*(X_with_ones.T.dot(X_with_ones.dot(theta)-y))
gfx_2 = 2*(X_with_ones.T.dot(X_with_ones.dot(theta)-y))/y.shape[0]

print('gfx by tf:',gfx)
print('manual gfx:', gfx_2)



gfx by tf: tf.Tensor(
[[-9.6852368e+07]
 [-4.7625093e+10]
 [-4.9149059e+10]
 [-5.4443177e+12]], shape=(4, 1), dtype=float32)
manual gfx: [[-9.68523814e+07]
 [-4.76250885e+10]
 [-4.91490526e+10]
 [-5.44431686e+12]]


In [ ]:
X_with_ones
# theta = np.random.normal(size=X_with_ones.shape[1]).reshape((X_with_ones.shape[1], 1))
hypo = X_with_ones.dot(theta)
y =  np.array(y).reshape(hypo.shape[0], 1)


# #step1: khai bao constant
X = tf.constant(X_with_ones,dtype=tf.float32)
theta = tf.constant(theta,dtype=tf.float32)
y = tf.constant(y,dtype=tf.float32)
with tf.GradientTape(persistent=True) as g:
#    # persistent = True de watch dc nhieu bien
   g.watch(X)
   g.watch(theta)
   g.watch(y)
   f = tf.square(tf.matmul(X,theta) - y)
   f = tf.reduce_mean(tf.matmul(X,theta) - y)
   gfx = g.gradient(f,theta)
  #  jftheta = g.jacobian(f,theta)

# print(f)
# print()

# gfx_2 = 2*(X_with_ones.T.dot(X_with_ones.dot(theta)-y))

print('gfx by tf:',gfx)
# print('manual gfx:', gfx_2)



gfx by tf: tf.Tensor(
[[1.0000000e+00]
 [5.0218252e+03]
 [1.2394750e+03]
 [1.1003251e+03]], shape=(4, 1), dtype=float32)


In [ ]:
learning_rate = 0.01
epochs = 1000

# X = np.array([
#     [2],
#     [7],
#     [9],
#     [3],
#     [10],
#     [6],
#     [1],
#     [8]
# ]
# )
# ones = np.ones_like(X)
# y = np.array([
#     [13],
#     [35],
#     [41],
#     [19],
#     [45],
#     [28],
#     [10],
#     [55]
# ])
# X_with_ones = np.concatenate ((X,ones), axis =1)
theta = np.random.normal(size=X_with_ones.shape[1]).reshape((X_with_ones.shape[1], 1))
# theta = np.array([[1],[1]])
hypo = X_with_ones.dot(theta)
y =  np.array(y).reshape(hypo.shape[0], 1)



print(X)
print('Theta', theta)
print(y)

for i in range(0,epochs):
  X = tf.constant(X_with_ones,dtype=tf.float32)
  theta = tf.constant(theta,dtype=tf.float32)
  print(theta)
  y = tf.constant(y,dtype=tf.float32)
  with tf.GradientTape(persistent=True) as g:
#    # persistent = True de watch dc nhieu bien
    g.watch([X,theta,y])
    # g.watch(theta)
    # g.watch(y)
    #  f = tf.square(tf.matmul(X,theta) - y)
    loss = tf.square(tf.matmul(X,theta) - y)

    f = tf.reduce_mean(loss)
    gfx = g.gradient(f,theta)
    print('grad', gfx)

    theta = theta - learning_rate * gfx
    print('Theta', theta)
  print('loss:', f/2)
  print(theta)
# print(i)

Streaming output truncated to the last 5000 lines.
 [0.31298873]
 [1.1204035 ]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[3.8762743 ]
 [0.37795085]
 [0.31298873]
 [1.1204035 ]], shape=(4, 1), dtype=float32)
grad tf.Tensor(
[[-0.09359387]
 [ 0.05662489]
 [ 0.05430133]
 [ 0.06563114]], shape=(4, 1), dtype=float32)
Theta tf.Tensor(
[[3.8772104]
 [0.3773846]
 [0.3124457]
 [1.1197472]], shape=(4, 1), dtype=float32)
loss: tf.Tensor(4.1234827, shape=(), dtype=float32)
tf.Tensor(
[[3.8772104]
 [0.3773846]
 [0.3124457]
 [1.1197472]], shape=(4, 1), dtype=float32)
tf.Tensor(
[[3.8772104]
 [0.3773846]
 [0.3124457]
 [1.1197472]], shape=(4, 1), dtype=float32)
grad tf.Tensor(
[[-0.09350397]
 [ 0.05657447]
 [ 0.05424657]
 [ 0.06556708]], shape=(4, 1), dtype=float32)
Theta tf.Tensor(
[[3.8781455 ]
 [0.37681887]
 [0.31190324]
 [1.1190915 ]], shape=(4, 1), dtype=float32)
loss: tf.Tensor(4.123387, shape=(), dtype=float32)
tf.Tensor(
[[3.8781455 ]
 [0.37681887]
 [0.31190324]
 [1.1190915 ]], shape=(4, 1), 

In [ ]:
# jftheta
theta

# y

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[4.135766  ],
       [0.24640715],
       [0.33083683],
       [0.7424877 ]], dtype=float32)>

In [ ]:
(X_with_ones.dot(theta) - y)
# theta

u = (1.0000*(-0.8131463) + 4.6161e+03*(-1.7262826) + 1.9594e+03*0.17742614 + 7.3140e+02*(-0.40178093) - 56358.8)
print('u:', u)
# u
2*u*(1.0000e+003) + 2*u*(4.6161e+03) + 2*u*(1.9594e+03) + 2*u*(7.3140e+02)
# 2*1.0000*-0.8131463 + 2*4.6161e+03*-1.7262826 + 2*1.9594e+03*0.17742614 + 2*7.3140e+02*-0.40178093
# y

u: -64274.520049646


-1067844021.2008088

In [ ]:
sum(2*(X_with_ones.dot(theta) - y))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-603281.25], dtype=float32)>

In [ ]:
(X_with_ones.dot(theta) - y)

X_with_ones

2*(1.0000e+00*-0.8131463 + 4.6161e+03*-1.7262826 + 9.0490e+02 *0.17742614 + 1.4564e+03*-0.40178093 - 72721.8)
2*(1.0000e+00*-0.8131463 + 5.8639e+03*-1.7262826  + 1.3272e+03*0.17742614 + 7.6010e+02*-0.40178093 - 87023.9)

-194434.75079264998

In [ ]:
theta

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.8131463 ],
       [-1.7262826 ],
       [ 0.17742614],
       [-0.40178093]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[72721.8],
       [87023.9],
       [52841.4],
       [53485.2]], dtype=float32)>

In [ ]:
theta

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.8131463 ],
       [-1.7262826 ],
       [ 0.17742614],
       [-0.40178093]], dtype=float32)>

In [ ]:
# buoc 1: tạo vector theta
theta = np.random.normal(size=X_with_ones.shape[1]).reshape((X_with_ones.shape[1], 1))
print(theta)

[[-0.90729836]
 [ 0.0519454 ]
 [ 0.72909056]
 [ 0.12898291]]


In [ ]:
# Buoc 2: tạo hàm hypo
def linear_regression(X_with_ones,theta):
  return X_with_ones.dot(theta)

In [ ]:
hypo = linear_regression(X_with_ones,theta)

In [ ]:
# bước 3: tạo hàm Loss Function
def mean_square_error(hypo,y):
  y =  np.array(y).reshape(hypo.shape[0], 1) # chuyển y từ vector thành MAT cùng chiều với hypo
  mse = (hypo-y)**2
  return mse

loss = mean_square_error(hypo,y)

$$ \theta_j := \theta_j - \alpha \frac{\partial}{\partial \theta_j} J(\theta) $$

In [ ]:
# muon ham loss đạt cực tiểu ->
# cách 1: lấy đạo hàm của hàm loss giải đạo hàm tại f = 0 (normal equation)
# cách 2: sử dụng gradient decent cập nhật theta_new = theta_old - learning_rate * đạo hàm của loss_function
# ** đạo hàm của Loss function tại 1 điểm theta (hypo-y)**2 = đạo hàm riêng của f theo theta
# J(theta) đạo hàm trên 1 điểm dữ liệu ta có: (hypo-y)*xi
# ** tổng quát (hình trên)

loss

array([[2.98083285e+09],
       [2.79048179e+09],
       [5.64518558e+09],
       [2.92548836e+09],
       [3.28266586e+09],
       [4.01581558e+09],
       [6.77351692e+09],
       [2.71143132e+09],
       [6.76242780e+09],
       [2.80127734e+09],
       [7.77192468e+09],
       [4.52429811e+09],
       [7.73125426e+09],
       [5.31343428e+09],
       [6.29607172e+09],
       [2.55189914e+09],
       [3.62629659e+09],
       [2.85722477e+09],
       [3.60315139e+09],
       [2.83994286e+09]])

In [ ]:
X_with_ones
hypo = X_with_ones.dot(theta)
theta = np.random.normal(size=X_with_ones.shape[1]).reshape((X_with_ones.shape[1], 1))
y =  np.array(y).reshape(hypo.shape[0], 1)


# #step1: khai bao constant
X = tf.constant(X_with_ones,dtype=tf.float32)
theta = tf.constant(theta,dtype=tf.float32)
y = tf.constant(y,dtype=tf.float32)
with tf.GradientTape(persistent=True) as g:
#    # persistent = True de watch dc nhieu bien
   g.watch(X)
   g.watch(theta)
   g.watch(y)
  #  f = tf.square(tf.matmul(X,theta) - y)
   f = tf.math.reduce_mean(tf.square(tf.matmul(X,theta) - y))
   gfx = g.gradient(f,theta)
   jftheta = g.jacobian(f,theta)

print(f)
# print()

gfx_2 = (X_with_ones.T.dot(X_with_ones.dot(theta)-y))

print(gfx)
print(gfx_2)



tf.Tensor(5908357600.0, shape=(), dtype=float32)
tf.Tensor(
[[-1.5082031e+05]
 [-7.6846054e+08]
 [-1.8515896e+08]
 [-1.6339691e+08]], shape=(4, 1), dtype=float32)
[[-3.01640605e+05]
 [-1.53692098e+09]
 [-3.70317928e+08]
 [-3.26793834e+08]]


In [ ]:
f = tf.math.reduce_mean(tf.square(tf.matmul(X,theta) - y))
f = tf.square(tf.matmul(X,theta) - y)
f

<tf.Tensor: shape=(20, 1), dtype=float32, numpy=
array([[3.4983741e+09],
       [3.5344637e+09],
       [6.4570906e+09],
       [3.5415862e+09],
       [3.7140874e+09],
       [4.7479972e+09],
       [7.5772590e+09],
       [3.7508844e+09],
       [8.5521562e+09],
       [3.1710124e+09],
       [9.2515953e+09],
       [5.1413002e+09],
       [8.4873713e+09],
       [6.9004431e+09],
       [6.3857116e+09],
       [2.5510572e+09],
       [3.4080625e+09],
       [3.8601989e+09],
       [4.5067013e+09],
       [3.8861778e+09]], dtype=float32)>

In [ ]:
gfx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-2.9882492e+06],
       [-1.4919658e+10],
       [-3.4040041e+09],
       [-2.3775447e+09]], dtype=float32)>

In [ ]:
X_with_ones

array([[1.0000e+00, 4.6161e+03, 1.9594e+03, 7.3140e+02],
       [1.0000e+00, 5.8639e+03, 1.6184e+03, 8.2440e+02],
       [1.0000e+00, 5.0207e+03, 9.7680e+02, 1.1372e+03],
       [1.0000e+00, 4.5866e+03, 1.5830e+03, 3.7230e+02],
       [1.0000e+00, 3.6774e+03, 3.2470e+02, 1.1001e+03],
       [1.0000e+00, 5.3442e+03, 1.3158e+03, 1.1048e+03],
       [1.0000e+00, 3.7819e+03, 3.7240e+02, 5.5250e+02],
       [1.0000e+00, 7.1883e+03, 1.8949e+03, 4.5470e+02],
       [1.0000e+00, 7.7275e+03, 1.0915e+03, 6.7850e+02],
       [1.0000e+00, 3.3758e+03, 8.8790e+02, 7.3650e+02],
       [1.0000e+00, 6.4379e+03, 6.0270e+02, 9.8420e+02],
       [1.0000e+00, 4.4667e+03, 1.5710e+03, 8.2630e+02],
       [1.0000e+00, 4.7603e+03, 9.6670e+02, 1.4860e+03],
       [1.0000e+00, 7.4420e+03, 1.1800e+03, 4.2250e+02],
       [1.0000e+00, 1.0328e+03, 1.3570e+02, 5.5070e+02],
       [1.0000e+00, 1.1535e+03, 1.2735e+03, 4.9360e+02],
       [1.0000e+00, 6.5160e+02, 1.2630e+03, 1.0837e+03],
       [1.0000e+00, 6.7446e+03,

In [ ]:
2*(1.0000*(-0.8131463) + 4.6161e+03*(-1.7262826) + 1.9594e+03*0.17742614 + 7.3140e+02*(-0.40178093) - 56358.8 )

-128549.040099292

In [ ]:
X_with_ones

u = (1.0000*(-0.8131463) + 4.6161e+03*(-1.7262826) + 1.9594e+03*0.17742614 + 7.3140e+02*(-0.40178093) - 56358.8)
2*u*(1.0000)
# 2*1.0000*-0.8131463 + 2*4.6161e+03*-1.7262826 + 2*1.9594e+03*0.17742614 + 2*7.3140e+02*-0.40178093

-128549.040099292

In [ ]:
-2.9882492e+06

-2988249.2

In [ ]:
theta

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.8131463 ],
       [-1.7262826 ],
       [ 0.17742614],
       [-0.40178093]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(20, 1), dtype=float32, numpy=
array([[56358.8],
       [54415. ],
       [76253.2],
       [55527.3],
       [57863.3],
       [64749. ],
       [82839.7],
       [53884.1],
       [83517.8],
       [53843.9],
       [89058.4],
       [68746. ],
       [89070.4],
       [74193.8],
       [79570.5],
       [51567.5],
       [61312.3],
       [54807.9],
       [61845.6],
       [54749.1]], dtype=float32)>

In [ ]:
(X_with_ones.dot(theta)-y)**2

<tf.Tensor: shape=(20, 1), dtype=float32, numpy=
array([[3.4983741e+09],
       [3.5344637e+09],
       [6.4570906e+09],
       [3.5415862e+09],
       [3.7140874e+09],
       [4.7479962e+09],
       [7.5772590e+09],
       [3.7508844e+09],
       [8.5521562e+09],
       [3.1710124e+09],
       [9.2515953e+09],
       [5.1413002e+09],
       [8.4873713e+09],
       [6.9004431e+09],
       [6.3857116e+09],
       [2.5510572e+09],
       [3.4080625e+09],
       [3.8601989e+09],
       [4.5067013e+09],
       [3.8861778e+09]], dtype=float32)>

In [ ]:
gfx

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-2.8066915e+06],
       [-1.3932491e+10],
       [-3.1806756e+09],
       [-2.2321375e+09]], dtype=float32)>

In [ ]:
# jftheta

In [ ]:
hypo = linear_regression(X_with_ones,theta)
loss = mean_square_error(hypo,y)
gfx_2 = (X_with_ones.T.dot(hypo-y))
gfx_2

array([[-1.32553442e+06],
       [-6.49750309e+09],
       [-1.49425189e+09],
       [-1.05753309e+09]])

In [ ]:
# X_with_ones
theta

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[ 0.37642553],
       [-1.0994008 ],
       [ 0.2982382 ],
       [ 1.3263859 ]], dtype=float32)>

In [ ]:
tf.matmul(X_with_ones.T,tf.matmul(X,theta))
# hypo

InvalidArgumentError: ignored

In [ ]:
loss

array([[3.58548047e+09],
       [3.51474188e+09],
       [6.39566522e+09],
       [3.55257857e+09],
       [3.64210629e+09],
       [4.72879414e+09],
       [7.42238392e+09],
       [3.67457932e+09],
       [8.24238106e+09],
       [3.17117539e+09],
       [8.95875066e+09],
       [5.19722649e+09],
       [8.47213166e+09],
       [6.63619460e+09],
       [6.38955196e+09],
       [2.68331998e+09],
       [3.62575165e+09],
       [3.72614009e+09],
       [4.50328130e+09],
       [3.75388905e+09]])

In [ ]:
f

<tf.Tensor: shape=(20, 1), dtype=float32, numpy=
array([[3.5854807e+09],
       [3.5147418e+09],
       [6.3956659e+09],
       [3.5525786e+09],
       [3.6421064e+09],
       [4.7287941e+09],
       [7.4223836e+09],
       [3.6745795e+09],
       [8.2423813e+09],
       [3.1711754e+09],
       [8.9587507e+09],
       [5.1972260e+09],
       [8.4721311e+09],
       [6.6361948e+09],
       [6.3895516e+09],
       [2.6833201e+09],
       [3.6257516e+09],
       [3.7261402e+09],
       [4.5032812e+09],
       [3.7538890e+09]], dtype=float32)>

In [ ]:
x1 = [73., 93., 89., 96., 73.]
x2 = [80., 88., 91., 98., 66.]
x3 = [75., 93., 90., 100., 70.]
y = [152., 185., 180., 196., 142.]

# random weights
w1 = tf.Variable(tf.random.normal([1]))
w2 = tf.Variable(tf.random.normal([1]))
w3 = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))

# Hypothesis
h = w1 * x1 + w2 * x2 + w3 * x3 + b

In [ ]:
learning_rate = 0.00001

for e in range(1000):
    # Record the gradient history of the cost function
    with tf.GradientTape() as tape:
        h = w1 * x1 + w2 * x2 + w3 * x3 + b
        cost = tf.reduce_mean(tf.square(h - y))

    # Calculate the gradient of each weight
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1, w2, w3, b])

    # update the weight
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)

    if e % 100 == 0:
        print("epoch: {:5} | cost: {:12.4f}".format(e, cost.numpy()))

epoch:     0 | cost:    1487.8044
epoch:   100 | cost:      44.4949
epoch:   200 | cost:      42.2578
epoch:   300 | cost:      40.1381
epoch:   400 | cost:      38.1299
epoch:   500 | cost:      36.2269
epoch:   600 | cost:      34.4239
epoch:   700 | cost:      32.7156
epoch:   800 | cost:      31.0969
epoch:   900 | cost:      29.5632


In [ ]:
data = np.array([
    [73., 80., 75., 152.],
    [93., 88., 93., 185.],
    [89., 91., 90., 180.],
    [96., 98., 100., 196.],
    [73., 66., 70., 142. ]
], dtype=np.float32)

X = data[:, :-1]
y = data[:, [-1]]

In [ ]:
X_array = np.array(X)
X_with_ones = np.hstack((np.ones((X_array.shape[0], 1)), X_array))
# X = np.array(X_with_ones)
X = tf.constant(X_with_ones,dtype=tf.float32)

In [ ]:
W = tf.Variable(tf.random.normal(shape=[X.shape[1], 1]))
W =  tf.Variable(theta)

W = np.array([[ 48042093.63628903]
 ,[-2545.40533284]
 ,[-2426.64862722]
 ,[ 51.14865817]])
W =  tf.Variable(W,dtype='float32')

# array([-2545.40533284, -2426.64862722,    51.14865817])


# b = tf.Variable(tf.random.normal(shape=[1]))

# Replace hypothesis with predict function
def predict(X):
    return tf.matmul(X, W)
    # return tf.matmul(X, theta)

In [ ]:
theta
W
# tf.matmul(X, W)
X

<tf.Tensor: shape=(1000, 4), dtype=float32, numpy=
array([[1.00000e+00, 5.49300e+02, 5.93300e+02, 8.30367e+04],
       [1.00000e+00, 7.15500e+02, 1.11000e+01, 5.28476e+04],
       [1.00000e+00, 6.03200e+02, 4.76400e+02, 5.70840e+04],
       ...,
       [1.00000e+00, 9.38500e+02, 4.80600e+02, 3.91252e+04],
       [1.00000e+00, 2.29400e+02, 6.44200e+02, 8.32191e+04],
       [1.00000e+00, 6.77500e+02, 5.02300e+02, 7.27660e+04]],
      dtype=float32)>

In [ ]:
# X = tf.constant(X_with_ones,dtype=tf.float32)

In [ ]:
tf.matmul(X, W)

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[-61.13117 ],
       [-82.92134 ],
       [-76.59425 ],
       [-87.54869 ],
       [-61.962887]], dtype=float32)>

In [ ]:
with tf.GradientTape() as tape:
  cost = tf.reduce_mean(tf.square(predict(X) - y))
  W_grad = tape.gradient(cost,W)
W - learning_rate * W_grad

TypeError: ignored

In [ ]:
W

<tf.Variable 'Variable:0' shape=(4, 1) dtype=float64, numpy=
array([[  17.288267],
       [7377.3887  ],
       [7138.4272  ],
       [ 617.75964 ]])>

In [ ]:
learning_rate = 0.0000000001

for e in range(10000):
    W = tf.Variable(W)

    # Record the gradient history of the cost function
    with tf.GradientTape() as tape:
        cost = tf.reduce_mean(tf.square(predict(X) - y))

    # Calculate the gradient of each weight
    # W_grad, b_grad = tape.gradient(cost, [W, b])
    W_grad = tape.gradient(cost, W)
    # print(W_grad)

    # update the weight
    # W.assign_sub(learning_rate * W_grad)
    W = W - learning_rate * W_grad
    # b.assign_sub(learning_rate * b_grad)

    if e % 100 == 0:
      print(W)
      print("epoch: {:5} | cost: {:12.4f}".format(e, cost.numpy()))

tf.Tensor(
[[ 4.8042092e+07]
 [-2.5453599e+03]
 [-2.4266062e+03]
 [ 4.4275097e+01]], shape=(4, 1), dtype=float32)
epoch:     0 | cost: 821263513681920.0000
tf.Tensor(
[[ 4.8042092e+07]
 [-2.5358347e+03]
 [-2.4171670e+03]
 [ 4.1832001e+01]], shape=(4, 1), dtype=float32)
epoch:   100 | cost: 820930116845568.0000
tf.Tensor(
[[ 4.8042092e+07]
 [-2.5263250e+03]
 [-2.4077471e+03]
 [ 4.1690903e+01]], shape=(4, 1), dtype=float32)
epoch:   200 | cost: 820912265887744.0000
tf.Tensor(
[[ 4.8042092e+07]
 [-2.5168472e+03]
 [-2.3983599e+03]
 [ 4.1550285e+01]], shape=(4, 1), dtype=float32)
epoch:   300 | cost: 820894482038784.0000
tf.Tensor(
[[ 4.8042092e+07]
 [-2.5074062e+03]
 [-2.3890054e+03]
 [ 4.1410187e+01]], shape=(4, 1), dtype=float32)
epoch:   400 | cost: 820876765298688.0000
tf.Tensor(
[[ 4.8042092e+07]
 [-2.4979963e+03]
 [-2.3796875e+03]
 [ 4.1270592e+01]], shape=(4, 1), dtype=float32)
epoch:   500 | cost: 820859182776320.0000
tf.Tensor(
[[ 4.8042092e+07]
 [-2.4886201e+03]
 [-2.3704009e+03]

In [ ]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


# X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])

# y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
reg.score(X, y)
# 1.0
reg.coef_
# array([1., 2.])
reg.intercept_
# 3.0...
# >>> reg.predict(np.array([[3, 5]]))
# array([16.])

# array([-2545.40533284, -2426.64862722,    51.14865817])
# 48042093.63628903

48042093.63628903

In [ ]:
reg

LinearRegression()

In [ ]:
# reg.score(X, y)

mse = mean_squared_error(reg.predict(X[:2]), y[:2], squared=True)
# X
# X
# reg.score(np.array(X), y)
# y[:1]
# reg.predict(X[:2])

y[:2]

print(mse)
print((math.sqrt((49451387.64011574 - 41402109.9)**2) + math.sqrt((48897004.14827105 - 62965534.1)**2))/2)

# 131357203570108.73

131357203570108.62
11058903.845922347


In [ ]:
import math
W = np.array([[ 48042093.63628903]
 ,[-2545.40533284]
 ,[-2426.64862722]
 ,[ 51.14865817]])

sum(np.sqrt(((X_with_ones@W)-np.array(y).reshape(1000,1))**2))/1000

# W

# 1.00000e+00*48042093.63628903 + 5.49300e+02*-2545.40533284 + 5.93300e+02*-2426.64862722 + 8.30367e+04*51.14865817
# 49451387.64029523

# reg.predict(X)

# X
# X_with_ones
# np.array(X)@np.array(reg.coef_)+reg.intercept_
# sum((reg.predict(X)-np.array(y))**2)/1000
# 815561254870254.1
8.15561255e+14

815561255000000.0